Fix Issue #3004 for mpi=no

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -25,11 +25,6 @@ default_build_public="no"
 build_version=$default_build_version
 build_public=$default_build_public
 
-# NCCL communication library
-have_nccl=no
-nccl_path=
-nccl_check=include/nccl.h
-
 # MKLML Version
 mklml_version=mklml_lnx_2018.0.1.20171227
 
@@ -111,6 +106,11 @@ mathlib=
 
 have_mpi=yes
 default_use_mpi=$have_mpi
+
+# NCCL communication library
+have_nccl=$have_mpi
+nccl_path=
+nccl_check=include/nccl.h
 
 default_use_code_coverage=no
 enable_code_coverage=$default_use_code_coverage
@@ -596,6 +596,7 @@ do
             if test x$optarg = xyes || test x$optarg = xno
             then
                 have_mpi=$optarg
+                have_nccl=$have_mpi
             else
                 echo "Invalid value for --mpi $optarg"
                 show_help
@@ -722,24 +723,27 @@ do
             fi
             ;;
         --with-nccl*)
-            have_nccl=yes
-            if test x$optarg = x
+            have_nccl=$have_mpi
+            if test $have_nccl = yes
             then
-                nccl_path=$(find_nccl)
-                if test x$nccl_path = x
+                if test x$optarg = x
                 then
-                    echo "Cannot find NCCL directory."
-                    echo "Please specify a value for --with-nccl"
-                    echo "NCCL can be downloaded from https://github.com/NVIDIA/nccl"
-                    exit 1
-                fi
-            else
-                if test $(check_dir $optarg $nccl_check) = yes
-                then
-                    nccl_path=$optarg
+                    nccl_path=$(find_nccl)
+                    if test x$nccl_path = x
+                    then
+                        echo "Cannot find NCCL directory."
+                        echo "Please specify a value for --with-nccl"
+                        echo "NCCL can be downloaded from https://github.com/NVIDIA/nccl"
+                        exit 1
+                    fi
                 else
-                    echo "Invalid NCCL directory $optarg"
-                    exit 1
+                    if test $(check_dir $optarg $nccl_check) = yes
+                    then
+                        nccl_path=$optarg
+                    else
+                        echo "Invalid NCCL directory $optarg"
+                        exit 1
+                    fi
                 fi
             fi
             ;;
@@ -1083,7 +1087,7 @@ then
     done
 fi
 
-if test $enable_cuda = yes && test x$nccl_path = x
+if test $enable_cuda = yes && test $have_nccl = yes && test x$nccl_path = x
 then
     nccl_path=$(find_nccl)
     if test x$nccl_path != x; then
